# Python as a calculator by using REPL
# REPL means Read Evaluate Print Loop
# It will run only those program which is valid according to python language. if not valid then it will give you error.....