name = "Yash"
print(len(name))

print(name.endswith("sh"))    # endswith used to determine whether it's satisfy the given condition or not.....
print(name.startswith("Ya"))   # startswith used to determine whether it's satisfy the given condition or not.....

Name = "Yash rajput"
print(Name.capitalize())  # Used to make the first left most letter of string into capital letter while others are small.....

print(Name.title())   # Use to first most letter of each character into capital letter.....

print(Name.upper())  # Use to capitalise all the letters of all the characters of a given string.....

print(Name.lower())   # Use to small all the letters of all the character of a given string.....

s = "hello world"
index = s.find("w")   # Use to find the indexing of selected letter or firstmost letter of selected string.....
print(index)
index = s.find("world")
print(index)

r = "hello world"
replace_string = s.replace("world", "Yash Rajput")  # s.replace() is used to replace the character from the sentence of a string.....
print(replace_string)