a = "Yash is a good and brave warrior\nnot a bad boy"
print(a)    # \n is an special character of escape sequence which makes printing in new line.....

b = "Yash will fight \t for the truth and fight \t alone till his last breathe"
print(b)    # \t will give you a space of 4 tabs.....

c = "Yash is an \"excellent\" boy"
print(c)    # \"x\" is used to put double coat in a double coated string.....

d = 'Yash is an \'excellent\' boy'
print(d)   # \'x\' is used to put single coat in a single coated string.....
           # Note:-> You can also print string in single coat.....
e = "Iswar sarvvyapi 'sarvshaktiman' hai"          # Note:-> you can normally put single coat in a double coated string.....
print(e)