friend = ["Apple", "Orange", 5, 65.76, False, "Akash", "Rohan"]                                                
print(friend)

friend.append("Yash")  # list.append() is used to add another element at the end in the list.....
print(friend)

l1 = [1,3,6,9,34]
l1.sort() # l.sort() used to arrange data in ascending order.....
print(l1)

l1.reverse()  # l.reverse() is used to arrange data in descending order.....
print(l1)

l1.insert(3,"warrior")  # l1.insert(x,y) is used to add another element in a list at any given position or indexing.....
                        # where x is indexing position and y is the element you want to add.....
print(l1)

l1.pop()   # l.pop() is used to remove element from list at the end or from any position from the list......
print(l1)

l1.pop(2)   # l.pop(x) is used to remove the element from the list at the given indexing position x.....
print(l1)

print(l1.pop(2))  # This type of function used to remove the element from the list when called print(x.y()) where x.y() van be anything.....
print(l1)

# We can change the origional value of list because it is mutable.....

l1.remove(34)  # l.remove(x) is used to remove the element x which is present in the list.....
print(l1)